### ISSUE TITLE
nastily Typo in README.md : jsonpikle vs jsonpickle

### ISSUE THREAD

**Issue by AlbertMietus** [atolab/python-cdds#1]
The readme has a nasty typo: A 'c' is missing in jsonpickle ...

The links is correct, the text is not -- Using the C&P on the text, I count install it (sic)

Was:
| - [**jsonpikle**](https://github.com/jsonpickle/jsonpickle), please refer to the project page for installation informations.

Should be:

| - [**jsonpickle**](https://github.com/jsonpickle/jsonpickle), please refer to the project page for installation informations.

Note: Github is also showing the 3 commands-block wrongly -- I can't see what wrong on the MD however.

Thanks --Albert

**Comment by gabrik** [comment]
Thanks that was fixed
